### ISSUE TITLE
q5 is broken after 2.7.7 ?

### ISSUE THREAD

**Issue by rjsworking** [q5js/q5.js#80]
hi
it looks like something has changed because even a simple sketch with a point( x, y ) does nothing
the last working version is 2.7.7

cheers
rjsworking

**Comment by quinton-ashley** [comment]
It works but maybe you can't see the point. The default stroke weight is so small you could mistake a pixel for a spec of dust.

Try using `strokeWeight` to increase the size of the point so that you can see it more easily.

Points are now made using canvas2d line strokes for better performance instead of arcs, so if what you really want is a 1x1 rect use the `rect` instead.
